/**
 * KCET Compass - Export Utilities
 * CSV and PDF export functions
 */

/**
 * Export data as CSV
 */
export function exportToCSV(results, filename = 'kcet-compass-results') {
  const headers = [
    'College Name',
    'Branch',
    'City',
    'Latest Cutoff',
    'Your Rank',
    'Difference',
    'Probability %',
    'Category',
    'Trend',
    'Tier',
  ];

  const rows = results.map(r => [
    `"${r.collegeName}"`,
    `"${r.branchName}"`,
    `"${r.city}"`,
    r.latestCutoff || 'N/A',
    r.rank || '',
    r.difference !== null ? r.difference : 'N/A',
    r.probability !== null ? `${r.probability}%` : 'N/A',
    r.probCategory || '',
    r.trend?.label || '',
    r.tier?.label || '',
  ]);

  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');

  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  link.href = URL.createObjectURL(blob);
  link.download = `${filename}.csv`;
  link.click();
  URL.revokeObjectURL(link.href);
}

/**
 * Export data as PDF
 */
export async function exportToPDF(results, studentInfo, filename = 'kcet-compass-results') {
  // Dynamically import jspdf and autotable
  const { default: jsPDF } = await import('jspdf');
  await import('jspdf-autotable');

  const doc = new jsPDF('l', 'mm', 'a4');

  // Title
  doc.setFontSize(20);
  doc.setTextColor(245, 166, 35);
  doc.text('KCET Compass - Analysis Report', 14, 20);

  // Student info
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Rank: ${studentInfo.rank} | Category: ${studentInfo.category} | Branch: ${studentInfo.branch} | City: ${studentInfo.city} | Round: ${studentInfo.round}`, 14, 30);

  doc.setDrawColor(245, 166, 35);
  doc.setLineWidth(0.5);
  doc.line(14, 33, 283, 33);

  // Table data
  const tableData = results.map(r => [
    r.collegeName,
    r.branchName,
    r.city,
    r.latestCutoff || 'N/A',
    r.difference !== null ? (r.difference > 0 ? `+${r.difference}` : r.difference) : 'N/A',
    r.probability !== null ? `${r.probability}%` : 'N/A',
    r.trend?.label || '',
    r.tier?.label || '',
  ]);

  doc.autoTable({
    startY: 38,
    head: [['College', 'Branch', 'City', 'Cutoff', 'Difference', 'Chance', 'Trend', 'Tier']],
    body: tableData,
    styles: {
      fontSize: 8,
      cellPadding: 2,
    },
    headStyles: {
      fillColor: [245, 166, 35],
      textColor: 255,
      fontStyle: 'bold',
    },
    alternateRowStyles: {
      fillColor: [255, 253, 247],
    },
    columnStyles: {
      0: { cellWidth: 60 },
      1: { cellWidth: 40 },
      5: { halign: 'center' },
      7: { halign: 'center' },
    },
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by KCET Compass | Page ${i} of ${pageCount}`, 14, doc.internal.pageSize.height - 10);
  }

  doc.save(`${filename}.pdf`);
}
